# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'change_bg_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChangeBgWindow(object):
    def setupUi(self, ChangeBgWindow):
        ChangeBgWindow.setObjectName("ChangeBgWindow")
        ChangeBgWindow.resize(580, 528)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ChangeBgWindow.sizePolicy().hasHeightForWidth())
        ChangeBgWindow.setSizePolicy(sizePolicy)
        ChangeBgWindow.setStyleSheet("#centralwidget {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:1px solid darkGray;\n"
"     border-radius:10px;\n"
"      /*border-bottom-right-radius:10px;*/\n"
"}")
        self.centralwidget = QtWidgets.QWidget(ChangeBgWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setToolTipDuration(-1)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.close_button = QtWidgets.QPushButton(self.widget_3)
        self.close_button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_button.sizePolicy().hasHeightForWidth())
        self.close_button.setSizePolicy(sizePolicy)
        self.close_button.setMinimumSize(QtCore.QSize(0, 0))
        self.close_button.setMaximumSize(QtCore.QSize(12, 12))
        self.close_button.setStyleSheet("QPushButton{background:#F76677;border-radius:6px;}QPushButton:hover{background:red;}")
        self.close_button.setText("")
        self.close_button.setIconSize(QtCore.QSize(0, 0))
        self.close_button.setCheckable(False)
        self.close_button.setObjectName("close_button")
        self.horizontalLayout_2.addWidget(self.close_button)
        self.mini_button = QtWidgets.QPushButton(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mini_button.sizePolicy().hasHeightForWidth())
        self.mini_button.setSizePolicy(sizePolicy)
        self.mini_button.setMaximumSize(QtCore.QSize(12, 12))
        self.mini_button.setStyleSheet("QPushButton{background:#F7D674;border-radius:6px;}QPushButton:hover{background:yellow;}")
        self.mini_button.setText("")
        self.mini_button.setIconSize(QtCore.QSize(0, 0))
        self.mini_button.setObjectName("mini_button")
        self.horizontalLayout_2.addWidget(self.mini_button)
        self.verticalLayout.addWidget(self.widget_3)
        self.widget_6 = QtWidgets.QWidget(self.centralwidget)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_7 = QtWidgets.QWidget(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_7.sizePolicy().hasHeightForWidth())
        self.widget_7.setSizePolicy(sizePolicy)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.img_name = QtWidgets.QLabel(self.widget_7)
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(12)
        self.img_name.setFont(font)
        self.img_name.setObjectName("img_name")
        self.horizontalLayout_4.addWidget(self.img_name)
        self.verticalLayout_4.addWidget(self.widget_7)
        self.widget_4 = QtWidgets.QWidget(self.widget_6)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_2 = QtWidgets.QWidget(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(9, -1, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.result_label = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result_label.sizePolicy().hasHeightForWidth())
        self.result_label.setSizePolicy(sizePolicy)
        self.result_label.setMinimumSize(QtCore.QSize(376, 376))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.result_label.setFont(font)
        self.result_label.setStyleSheet("QLabel{\n"
"border:2px dashed darkGray;\n"
"border-radius:10px;\n"
"}")
        self.result_label.setAlignment(QtCore.Qt.AlignCenter)
        self.result_label.setObjectName("result_label")
        self.verticalLayout_2.addWidget(self.result_label)
        self.horizontalLayout.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(self.widget_4)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_5 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget_5.setStyleSheet("border:2px dashed darkGray;\n"
"border-radius:10px;")
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.red_button = QtWidgets.QPushButton(self.widget_5)
        self.red_button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.red_button.sizePolicy().hasHeightForWidth())
        self.red_button.setSizePolicy(sizePolicy)
        self.red_button.setMinimumSize(QtCore.QSize(26, 26))
        self.red_button.setMaximumSize(QtCore.QSize(26, 26))
        self.red_button.setStyleSheet("QPushButton{background:#F76677;border-radius:6px;border:2px solid black;}QPushButton:hover{background:rgb(226, 93, 111);}")
        self.red_button.setText("")
        self.red_button.setIconSize(QtCore.QSize(0, 0))
        self.red_button.setCheckable(False)
        self.red_button.setObjectName("red_button")
        self.horizontalLayout_3.addWidget(self.red_button)
        self.blue_button = QtWidgets.QPushButton(self.widget_5)
        self.blue_button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blue_button.sizePolicy().hasHeightForWidth())
        self.blue_button.setSizePolicy(sizePolicy)
        self.blue_button.setMinimumSize(QtCore.QSize(26, 26))
        self.blue_button.setMaximumSize(QtCore.QSize(26, 26))
        self.blue_button.setStyleSheet("QPushButton{background:rgb(85, 170, 255);border-radius:6px;border:2px solid black;}QPushButton:hover{background:rgb(77, 155, 232);}")
        self.blue_button.setText("")
        self.blue_button.setIconSize(QtCore.QSize(0, 0))
        self.blue_button.setCheckable(False)
        self.blue_button.setObjectName("blue_button")
        self.horizontalLayout_3.addWidget(self.blue_button)
        self.white_button = QtWidgets.QPushButton(self.widget_5)
        self.white_button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.white_button.sizePolicy().hasHeightForWidth())
        self.white_button.setSizePolicy(sizePolicy)
        self.white_button.setMinimumSize(QtCore.QSize(26, 26))
        self.white_button.setMaximumSize(QtCore.QSize(26, 26))
        self.white_button.setStyleSheet("QPushButton{\n"
"background:rgb(255, 255, 255);\n"
"border-radius:6px;\n"
"border:2px solid black;\n"
"}\n"
"QPushButton:hover{background:rgb(243, 243, 243);}")
        self.white_button.setText("")
        self.white_button.setIconSize(QtCore.QSize(0, 0))
        self.white_button.setCheckable(False)
        self.white_button.setObjectName("white_button")
        self.horizontalLayout_3.addWidget(self.white_button)
        self.verticalLayout_3.addWidget(self.widget_5)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.clear_button = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(12)
        self.clear_button.setFont(font)
        self.clear_button.setStyleSheet("QPushButton{\n"
"background:#F7D674;\n"
"border-radius:6px;\n"
"padding-top:6px;\n"
"padding-bottom:6px;\n"
"padding-left:12px;\n"
"padding-right:12px;\n"
"border:2px solid black;\n"
"}\n"
"QPushButton:hover{\n"
"background:yellow;\n"
"}")
        self.clear_button.setObjectName("clear_button")
        self.verticalLayout_3.addWidget(self.clear_button)
        self.ok_button = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(12)
        self.ok_button.setFont(font)
        self.ok_button.setStyleSheet("QPushButton{\n"
"background:#F7D674;\n"
"border-radius:6px;\n"
"padding-top:6px;\n"
"padding-bottom:6px;\n"
"padding-left:12px;\n"
"padding-right:12px;\n"
"border:2px solid black;\n"
"}\n"
"QPushButton:hover{\n"
"background:yellow;\n"
"}")
        self.ok_button.setObjectName("ok_button")
        self.verticalLayout_3.addWidget(self.ok_button)
        self.horizontalLayout.addWidget(self.widget)
        self.verticalLayout_4.addWidget(self.widget_4)
        self.verticalLayout.addWidget(self.widget_6)
        ChangeBgWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ChangeBgWindow)
        self.statusbar.setObjectName("statusbar")
        ChangeBgWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ChangeBgWindow)
        QtCore.QMetaObject.connectSlotsByName(ChangeBgWindow)

    def retranslateUi(self, ChangeBgWindow):
        _translate = QtCore.QCoreApplication.translate
        ChangeBgWindow.setWindowTitle(_translate("ChangeBgWindow", "Change Background"))
        self.img_name.setText(_translate("ChangeBgWindow", "TextLabel"))
        self.result_label.setText(_translate("ChangeBgWindow", "RESULT"))
        self.clear_button.setText(_translate("ChangeBgWindow", "CLEAR"))
        self.ok_button.setText(_translate("ChangeBgWindow", "OK"))
