# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(880, 952)
        MainWindow.setStyleSheet("#centralwidget {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:1px solid darkGray;\n"
"     border-radius:10px;\n"
"      /*border-bottom-right-radius:10px;*/\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setToolTipDuration(-1)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.close_button = QtWidgets.QPushButton(self.widget)
        self.close_button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_button.sizePolicy().hasHeightForWidth())
        self.close_button.setSizePolicy(sizePolicy)
        self.close_button.setMinimumSize(QtCore.QSize(0, 0))
        self.close_button.setMaximumSize(QtCore.QSize(12, 12))
        self.close_button.setStyleSheet("QPushButton{background:#F76677;border-radius:6px;}QPushButton:hover{background:red;}")
        self.close_button.setText("")
        self.close_button.setIconSize(QtCore.QSize(0, 0))
        self.close_button.setCheckable(False)
        self.close_button.setObjectName("close_button")
        self.horizontalLayout_2.addWidget(self.close_button)
        self.mini_button = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mini_button.sizePolicy().hasHeightForWidth())
        self.mini_button.setSizePolicy(sizePolicy)
        self.mini_button.setMaximumSize(QtCore.QSize(12, 12))
        self.mini_button.setStyleSheet("QPushButton{background:#F7D674;border-radius:6px;}QPushButton:hover{background:yellow;}")
        self.mini_button.setText("")
        self.mini_button.setIconSize(QtCore.QSize(0, 0))
        self.mini_button.setObjectName("mini_button")
        self.horizontalLayout_2.addWidget(self.mini_button)
        self.verticalLayout.addWidget(self.widget)
        self.tool_bar = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tool_bar.sizePolicy().hasHeightForWidth())
        self.tool_bar.setSizePolicy(sizePolicy)
        self.tool_bar.setObjectName("tool_bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tool_bar)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.tool_bar)
        self.label.setMinimumSize(QtCore.QSize(150, 0))
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Bauhaus 93")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(True)
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.title_image = QtWidgets.QPushButton(self.tool_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_image.sizePolicy().hasHeightForWidth())
        self.title_image.setSizePolicy(sizePolicy)
        self.title_image.setStyleSheet("QPushButton{\n"
"background:transparent;\n"
"}\n"
"QPushButton:hover{\n"
"color:rgb(71,186,204);\n"
"background:transparent;\n"
"}\n"
"QPushButton:pressed{\n"
"color:white;\n"
"background-color:rgb(71,186,204);\n"
"}\n"
"QPushButton:!enabled\n"
"{\n"
"color:rgb(130,130,130);\n"
"}\n"
"QPushButton:focus {\n"
"color:black;\n"
"background-color:white;\n"
"}")
        self.title_image.setText("")
        self.title_image.setObjectName("title_image")
        self.horizontalLayout.addWidget(self.title_image)
        self.title_trimap = QtWidgets.QPushButton(self.tool_bar)
        self.title_trimap.setStyleSheet("QPushButton{\n"
"background:transparent;\n"
"}\n"
"QPushButton:hover{\n"
"color:rgb(71,186,204);\n"
"background:transparent;\n"
"}\n"
"QPushButton:pressed{\n"
"color:white;\n"
"background-color:rgb(71,186,204);\n"
"}\n"
"QPushButton:!enabled\n"
"{\n"
"color:rgb(130,130,130);\n"
"}\n"
"QPushButton:focus {\n"
"color:black;\n"
"background-color:white;\n"
"}")
        self.title_trimap.setText("")
        self.title_trimap.setObjectName("title_trimap")
        self.horizontalLayout.addWidget(self.title_trimap)
        self.title_matting = QtWidgets.QPushButton(self.tool_bar)
        self.title_matting.setStyleSheet("QPushButton{\n"
"background:transparent;\n"
"}\n"
"QPushButton:hover{\n"
"color:rgb(71,186,204);\n"
"background:transparent;\n"
"}\n"
"QPushButton:pressed{\n"
"color:white;\n"
"background-color:rgb(71,186,204);\n"
"}\n"
"QPushButton:!enabled\n"
"{\n"
"color:rgb(130,130,130);\n"
"}\n"
"QPushButton:focus {\n"
"color:black;\n"
"background-color:white;\n"
"}")
        self.title_matting.setText("")
        self.title_matting.setObjectName("title_matting")
        self.horizontalLayout.addWidget(self.title_matting)
        self.title_cutout = QtWidgets.QPushButton(self.tool_bar)
        self.title_cutout.setStyleSheet("QPushButton{\n"
"background:transparent;\n"
"}")
        self.title_cutout.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.title_cutout.setIcon(icon)
        self.title_cutout.setObjectName("title_cutout")
        self.horizontalLayout.addWidget(self.title_cutout)
        self.verticalLayout.addWidget(self.tool_bar)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.content = QtWidgets.QWidget()
        self.content.setGeometry(QtCore.QRect(0, 0, 843, 18))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.content.sizePolicy().hasHeightForWidth())
        self.content.setSizePolicy(sizePolicy)
        self.content.setObjectName("content")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.content)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea.setWidget(self.content)
        self.verticalLayout.addWidget(self.scrollArea)
        self.hint = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.hint.setFont(font)
        self.hint.setStyleSheet("QPushButton#hint{\n"
"background-color: rgb(79, 79, 79);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:4px;\n"
"padding:8px;\n"
"}")
        self.hint.setObjectName("hint")
        self.verticalLayout.addWidget(self.hint)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Background Eraser"))
        self.label.setText(_translate("MainWindow", "BACKGROUND"))
        self.hint.setText(_translate("MainWindow", "hint"))
