# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'matting_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MattingForm(object):
    def setupUi(self, MattingForm):
        MattingForm.setObjectName("MattingForm")
        MattingForm.resize(576, 502)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(MattingForm)
        self.horizontalLayout_2.setSpacing(22)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.image_label = QtWidgets.QLabel(MattingForm)
        self.image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.image_label.setObjectName("image_label")
        self.horizontalLayout_2.addWidget(self.image_label)
        self.result_label = QtWidgets.QLabel(MattingForm)
        self.result_label.setAlignment(QtCore.Qt.AlignCenter)
        self.result_label.setObjectName("result_label")
        self.horizontalLayout_2.addWidget(self.result_label)

        self.retranslateUi(MattingForm)
        QtCore.QMetaObject.connectSlotsByName(MattingForm)

    def retranslateUi(self, MattingForm):
        _translate = QtCore.QCoreApplication.translate
        MattingForm.setWindowTitle(_translate("MattingForm", "Form"))
        self.image_label.setText(_translate("MattingForm", "aaaaaaaaaaaaaaaaaa"))
        self.result_label.setText(_translate("MattingForm", "bbbbbbbbbbbbbbbbb"))
